### ISSUE TITLE
indentation issues

### ISSUE THREAD

**Issue by chnadrasekharprabhakar** [ccht-ncsu/Kalpana#30]
Hi, I am a student trying to explore the Kalpana.
I have downloaded it from git. But looks to me like it has a lot of indentation issues while trying on hands-on with sample data provided.
could you please provide the file (kalpana.py) with the proper formatting?

Thank you.

**Comment by carucker** [comment]
Hello,

Are you opening the code in a Linux environment? Other operating systems
have a different number of spaces associated with tab (/t), so this is
likely the cause of your indentation issues.

If you are using Kalpana for downscaling, I would suggest using a Linux
environment because the downscaling portion of the code was developed for
Linux and will otherwise fail in several areas. If you are not downscaling,
indentation issues will exist in parts of the code that are not being run
and shouldn't raise an error.

Carter A. Rucker, EI
Coastal Engineer - Water Resources Section
Wilmington District
U.S. Army Corps of Engineers
69 Darlington Ave.
Wilmington, NC 28403
O: 910-251-4799
C: 919-605-0221

**Comment by msw09090** [comment]
Hello,

I still have this problem too (Linus - CentOS).

I used Kalpana.py from here (which worked... for the most part): https://github.com/Jiangchao3/Kalpana/tree/V0.1
